dist: trusty
language: java
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
- oraclejdk11
- openjdk10
- openjdk11
addons:
  sonarcloud:
    organization: "egorovpavel-github"
    token: $SONAR_KEY
script:
  - sonar-scanner
cache:
  directories:
  - '$HOME/.sonar/cache'